### ISSUE TITLE
Feature: Users can create a workspace

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#1]
## ⚙️ Feature

> ##### Users will be able to create workspaces so that they will be able to hold various boards within it.

## 📐 Functionality

> ##### Users will fill out the form for creating a workspace as well as being able to view a list of them

## 🖼️ Wireframes

![Screen Shot 2021-12-29 at 5 47 49 PM](https://user-images.githubusercontent.com/72685552/147715271-80e3e891-2f7d-47f9-ab27-36257b06699a.png)

![Screen Shot 2021-12-29 at 5 49 24 PM](https://user-images.githubusercontent.com/72685552/147715332-f95cca82-da76-4ece-91d3-b22a26160f72.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to sql code from db designer
- [x] Update `data.sql` to insert dummy data - if needed

### ☁️ Server

- [x] Update `server/index.js` to send data to workspace data table (post)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client. Remember to ensure form is filled out

### ⚡ Client

- [x] Create the page header for the app
- [x] Create a component to create a workspace form. The results should send a request to the server with input from user.
- [x] Update the form component to accept values and update state.
- [x] Make sure to prevent default behavior
- [x] Reset form values

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [x] Eliminate workspace type as it is not needed anymore
- [x] Ensure styling is identical or better than figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements - for create button
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
