### ISSUE TITLE
Feature: Users can create boards

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-02 at 3 54 17 PM](https://user-images.githubusercontent.com/72685552/147892634-e88aa428-d06e-457b-babb-8f29e56ada86.png)

![Screen Shot 2022-01-02 at 3 54 12 PM](https://user-images.githubusercontent.com/72685552/147892635-4d7eeb38-cbde-44df-85a4-b0eee2b6f558.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert dummy data for the boards table.

### ☁️ Server

- [x] Update `server/index.js` to handle post requests to the database for boards
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a standard message saying no boards are created for the workspace with a button on the bottom to create one
- [x] Create a form component creating a board after the user clicks on the button from top
- [x] Update component to accept values and update state
- [x] Ensure to prevent default behabior
- [x] Reset form values

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Ensure styling is identical or better than figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jonathanymatsuda** [comment]
Think about how boards will be nested in workspace based of workspaceId.
