### ISSUE TITLE
Feature: User can view a list of workspaces

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#26]
## ⚙️ Feature

Users will be able to view a list of all the workspaces they created in aggregate.

## 📐 Functionality

Users will be able to see all workspaces in one area.

## 🖼️ Wireframes

![Screen Shot 2021-12-30 at 8 52 58 AM](https://user-images.githubusercontent.com/72685552/147772158-602b29bb-0d96-4205-b752-c8bede916496.png)

![Screen Shot 2021-12-29 at 5 50 24 PM](https://user-images.githubusercontent.com/72685552/147715347-d2e633b5-5f2d-49db-ba51-f6055074ed88.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive data from workspace data table (get)
- [x] Query database to receive the necessary information
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create another component to render a list of workspaces created
- [x] Fetch request for data from the table
- [x] Update banner with app logo and the ability to click on active workspaces anchor tag from the form (if user chooses to do that)
- [x] Hash route the form and the workspace list view based off button click so user can see either or (this will involve the banner anchor tag and the +Create New Workspace to get back to the form)

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Ensure styling is identical or better than figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jonathanymatsuda** [comment]
Think about logic of "Active Workspaces" view when there are no boards created.
