### ISSUE TITLE
Feature: Users can create lists

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to create a list within a given board.

## 📐 Functionality

User will be able to click on a create list button and add as many lists as they want.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="518" alt="Screen Shot 2022-01-03 at 3 36 27 PM" src="https://user-images.githubusercontent.com/72685552/147991724-eb5250a0-5382-465b-b872-960a9c5cbe7a.png">
<img width="521" alt="Screen Shot 2022-01-03 at 3 36 18 PM" src="https://user-images.githubusercontent.com/72685552/147991725-334d4fc9-ec35-4a6a-802f-0349a6b7d57f.png">
<img width="524" alt="Screen Shot 2022-01-03 at 3 36 10 PM" src="https://user-images.githubusercontent.com/72685552/147991726-26531756-1b5f-49fb-ab72-ad32fb567315.png">
<img width="517" alt="Screen Shot 2022-01-03 at 3 35 58 PM" src="https://user-images.githubusercontent.com/72685552/147991727-9625e516-3537-49ca-b5ae-f5c87429f1ef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert dummy lists within boards.

### ☁️ Server

- [x] Update `server/index.js` to handle post requests to the database for lists.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a form component for creating a list after the user clicks on the botton to do so.
- [x] Update component to accept values and update state
- [x] Ensure to prevent default behavior
- [x] Reset form values
- [x] Ensure that the list renders automatically without a refresh and that the button will get pushed to the right.

### 🧑‍⚕️ Clean Up

- [x] Ensure styling is identical or better than figma
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
