### ISSUE TITLE
Feature: User can view boards

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view boards.

## 📐 Functionality

After creating boards, users will have the ability to view boards per workspace or in aggregate.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="520" alt="Screen Shot 2022-01-03 at 10 54 48 AM" src="https://user-images.githubusercontent.com/72685552/147968452-7271b03b-49cd-419d-9241-ea0f17aecce8.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive data from boards data table (get)
- [x] Query database to receive necessary information
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a list of boards (should be per workspace not all boards)
- [x] Fetch request for data from boards table
- [x] Hash routing should be in place but verify and change if needed.

### 🧑‍⚕️ Clean Up

- [x] Ensure styling is identical or better than figma.
- [x] Think about consistency of button colors and shapes.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
