### ISSUE TITLE
Feature: Users can create tasks

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can create tasks

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to create specific tasks within each column

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
 
![Screen Shot 2022-01-07 at 12 28 10 PM](https://user-images.githubusercontent.com/72685552/148603322-4da6118d-6ff8-4dec-9968-5e312c615004.png)

![Screen Shot 2022-01-07 at 12 30 00 PM](https://user-images.githubusercontent.com/72685552/148603363-711e5ea4-3cfd-40d1-bba8-0500e4090b7a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert dummy tasks

### ☁️ Server

- [x] Update `server/index.js` to handle post request for a task within a list/column
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for being able to create a task after the user clicks a plus icon
- [x] Update component to accept values and update state
- [x] Make sure to prevent default behavior
- [x] Reset form values
- [x] Ensure that tasks render automatically once a user adds them

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
