### ISSUE TITLE
Feature: Users can reorder lists with drag and drop

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/flexboard#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the ability to drag and drop lists that are created.

## 📐 Functionality

Users will be able to grab the header of the column and drag and drop to reorder lists

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-06 at 8 50 45 AM](https://user-images.githubusercontent.com/72685552/148419403-579cf9d6-b2a1-40f1-84ce-12eb4e546c69.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to make edits to the sort order of columns (Patch). 
  - [x] Patch route should take the whole array of lists regardless of board
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Npm install react-beautiful-dnd
- [x] Update the List component to be able to drag and drop by inserting draggable and droppable areas
- [x] Include an onDragEnd method in order for the columns to stay in place once a user drags
- [x] Update state so that columns stay on browser refresh

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
